### ISSUE TITLE
Download Folders

### ISSUE THREAD

**Issue by goldbattle** [Soartex/Texture-Patcher-v1#42]
Make sure that the temp download folders are clear. If there is a failed download sometimes there can already be mods/a texture pack in the temp folder. 

I'm not sure if it is checked if the directory is already clear, but it should check if it is created already, and if it is delete it.

Just a thought

**Comment by ghost** [comment]
If the program crashes/fails during patching, the folders will still exist. However, the patcher always deletes them before patching, so it shouldn't be a problem.

**Comment by goldbattle** [comment]
Ok. Just making sure. I couldn't find where they were deleted.

**Comment by ghost** [comment]
Theres a recursive delete method called right before any operation.
