### ISSUE TITLE
settings file for the texurepack you are using

### ISSUE THREAD

**Issue by Goten87** [Soartex/Texture-Patcher-v1#48]
i'm jusing the patcher for both soartex and john smith
but i always need to chance the texurepack for them both

exemple
if i updated soartex and wanne do the john smith
then i need to navigate to the john smit texurepack zip
will it not be eazyer if u make a setting file in the folder of the jar
so for john smit one it will load in then the john_settings.conf file in
and for the soartex it will be soartex_settings.conf

so it will take the name of the one your using with _settings.conf efter it

Greets Goten87

**Comment by ghost** [comment]
Hi Goten87,

While this feature would be a convenience, I am not sure it is possible due to each patcher being distributed separately but different texture packs, at different versions.
