### ISSUE TITLE
Problems opening launcher

### ISSUE THREAD

**Issue by ghost** [Soartex/Texture-Patcher-v1#49]
I have tried to get the patcher working for a bit and for some reason I can't figure it out. I have read the user guide and know the steps, but my problem is the file is downloading as a .zip. My friend Alf tried to help me and we got to the point that it was set to open with java. When I attempt to launch it some black window pops up for a split second and disappears, then nothing happens. I'm looking for all the help I can get to fix this. Sorry If I am being a bother to anyone.

**Comment by ghost** [comment]
Hi Backsmasherr, the file you downloading, what is it called exactly, along with the file extension?

**Comment by ghost** [comment]
The file I'm downloading is from the link on the Soartex site. The file name is Texture-Patcher-1.2.jar.

**Comment by ghost** [comment]
Ah, yep, you are downloading the blank version for use for Texture Pack
authors, try downloading the Soartex Texture Patcher.

On Friday, July 5, 2013, Backsmasherr wrote:

> The file I'm downloading is from the link on the Soartex site. The file
> name is Texture-Patcher-1.2.jar.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Soartex-Fanver/Texture-Patcher/issues/49#issuecomment-20528312
> .

## 

Regards,

Emmanuel Decaudin

**Comment by ghost** [comment]
Just tried downloading it again and the same thing happened. Is this the right page to download? http://soartex.net/downloads/

**Comment by ghost** [comment]
Yes, you did hit the "direct" link to the right of Texture Patcher, right?

On Friday, July 5, 2013, Backsmasherr wrote:

> Just tried downloading it again and the same thing happened. Is this the
> right page to download? http://soartex.net/downloads/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Soartex-Fanver/Texture-Patcher/issues/49#issuecomment-20528551
> .

## 

Regards,

Emmanuel Decaudin

**Comment by ghost** [comment]
Yes, I hit the direct link.

**Comment by goldbattle** [comment]
Are you using IE? If so please try another browser.

**Comment by ghost** [comment]
I am using Firefox. I'll try and download with different browsers and see if that helps.

**Comment by goldbattle** [comment]
The download shouldn't be that big of a deal. The thing that is making it seem like your java is not set up correctly is the cmd prompt popping up and not launching the program. Usually that happens when your java is outdated, has incorrect paths variables, or have an incompatible version of java.

**Comment by ghost** [comment]
Yes, the cmd prompt is what is showing up for a second. The Java version I have is Java 7 update 21 (64-bit).

**Comment by goldbattle** [comment]
I am not quite sure why this is happening. Does it happen with any of these from the archives?
http://files.soartex.net/texture-patcher/soartex/

**Comment by ghost** [comment]
It happened to all of them.

**Comment by goldbattle** [comment]
@REDX36 any ideas? I am out of them.

**Comment by ghost** [comment]
Do you get the same problem yourself Gold?

Regards,

Emmanuel Decaudin

**Comment by goldbattle** [comment]
Nope, works fine for me.

**Comment by treyappelgate** [comment]
I am having the same issue. This thing used to work fine. When I tried to open this windows asked me how I wanted to open it. Java was not listed so I went and tried both java.exe and javaw.exe and neither work. I can see the command box blink on and off and nothing. Whats going on. I really want the patcher for the other textures

**Comment by treyappelgate** [comment]
this seems to be happening with both kinds of patchers. I have a feeling its something with java or something conflicting with it

**Comment by goldbattle** [comment]
@kalaxal @Backsmasherr 

Can you try the windows version?
http://soartex.net/texture-patcher/

Thanks!
