### ISSUE TITLE
Can't open the Patcher

### ISSUE THREAD

**Issue by cwCoolHCI** [Soartex/Texture-Patcher-v1#51]
Hey there,
actually I downloaded the .jar file to Run it on Mac OX 10.8.4 but when i try to start the .jar it doesn't show any branches.

**Comment by goldbattle** [comment]
Where did you download it from? Was it from this page: http://soartex.net/texture-patcher/

You need to make sure you run it with Mac's version of java. I do not have a Mac so I can't give details.

**Comment by cwCoolHCI** [comment]
I downloaded it from that page (Other (.jar)).
Here's a picture.
![bildschirmfoto 2013-09-05 um 10 23 29](https://f.cloud.github.com/assets/5383832/1086706/99a633e2-1604-11e3-9551-703e90ce8b98.png)

**Comment by goldbattle** [comment]
Unable to fix.
