### ISSUE TITLE
Not seeing Java 8

### ISSUE THREAD

**Issue by APasz** [Soartex/Texture-Patcher-v1#55]
Like the title says, I'm running Java 8 update 5. Whenever I start it up, it tells me that no java was found and gives me the option to download Java.
And I would rather not install Java 7 as well.

**Comment by goldbattle** [comment]
Soon, we hope to remake this patcher. So I am not sure if it is worth going back and remaking that part.

Are you using the .exe or the .jar?
The .jar should work with all version of java. http://goo.gl/Pt04Jl
Also what operating system are you running on?

**Comment by artdude543** [comment]
Hey, could you try this version please http://dl.soartex.net/1gakr and report back if it works or not. Thanks
