### ISSUE TITLE
Patcher 2.1 not opening, no error

### ISSUE THREAD

**Issue by zenkmander** [Soartex/Texture-Patcher-v1#56]
Windows 8 x64
Java 8u5 64-bit

Nothing happens when I try to open the new patcher. Which Java exe does it utilize to open? It's using javaw at the moment. I've tried with a handful of other exes in the Java folder, still nothing.

**Comment by artdude543** [comment]
Hey, could you try this version please http://dl.soartex.net/1gakr and report back if it works or not. Thanks
